WDI.OEE/Controllers/FileController.cs
using Microsoft.AspNetCore.Mvc;

namespace WDI.OEE.Controllers
{
    public class FileController : Controller
    {
        private readonly IWebHostEnvironment _webHostEnvironment;

        public FileController(IWebHostEnvironment webHostEnvironment)
        {
            _webHostEnvironment = webHostEnvironment;
        }


        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> DownloadBlank(string fName)
        {
            var path = Path.Combine($"{_webHostEnvironment.WebRootPath}\\uploads\\documents\\Weldcom_blank.pdf");
            var memory = new MemoryStream();
            using (var stream = new FileStream(path, FileMode.Open))
            {
                await stream.CopyToAsync(memory);
            }
            memory.Position = 0;
            var ext = Path.GetExtension(fName).ToLowerInvariant();
            return File(memory, Common.FileExtension.GetMimeType(fName), Path.GetFileName(fName));
        }
    }
}

WDI.OEE/Controllers/MachineManagementController.cs
using Common.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json.Linq;
using Service.IService;

namespace WDI.OEE.Controllers
{
    /// <summary>
    /// Quản lý máy
    /// </summary>
    public class MachineManagementController : BaseController
    {
        private readonly IMachineManagementService _machineManagementService;
        private readonly IErrorMachineService _errorMachineService;
        private readonly IReportMachineRuningStatusService _reportMachineRuningStatusService;

        public MachineManagementController(IMachineManagementService machineManagementService, IErrorMachineService errorMachineService, IReportMachineRuningStatusService reportMachineRuningStatusService)
        {
            _machineManagementService = machineManagementService;
            _errorMachineService = errorMachineService;
            _reportMachineRuningStatusService = reportMachineRuningStatusService;
        }

        public ActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// Danh mục máy, có 2 param để open form từ các trang khác truyền vào
        /// </summary>
        /// <param name="machineGroupID"></param>
        /// <param name="workshopID"></param>
        /// <returns></returns>
        public ActionResult List(int machineGroupID = 0
            , int workshopID = 0
            , int machineAssetGroupID = 0
            , int machineLocationID = 0)
        {
            ViewData["machineGroupID"] = machineGroupID;
            ViewData["workshopID"] = workshopID;
            ViewData["machineAssetGroupID"] = machineAssetGroupID;
            ViewData["machineLocationID"] = machineLocationID;

            return View();
        }

        /// <summary>
        /// Thống kê số lượng máy
        /// </summary>
        /// <param name="stringData">string dạng JObject</param>
        /// <returns></returns>
        public ActionResult Statitics(string stringData)
        {
            MachineStatiticsViewModel model = new MachineStatiticsViewModel();
            ViewData["Title"] = "Thống kê số lượng máy";

            try
            {
                //dynamic d = JObject.Parse(stringData);
                //int machineID = d.machineID;
                //int machineLocationID = d.machineLocationID;

                model = _machineManagementService.GetStatitics();
            }
            catch (Exception)
            {

            }

            return View(model);
        }

        /// <summary>
        /// Load chi tiết máy
        /// </summary>
        /// <param name="stringData">
        /// Json data gồm các trường:
        /// <para>machineID: id máy</para>
        /// <para>machineLocationID: id vị trí lắp máy</para>
        /// <para>formType: kiểu form: 1=load to view; 2=load to edit</para>
        /// </param>
        /// <returns></returns>
        public ActionResult MachineDetail(string stringData)
        {
            MachineDetailViewModel model = new MachineDetailViewModel();
            ViewData["Title"] = "Xem chi tiết máy";

            try
            {
                dynamic d = JObject.Parse(stringData);
                int machineID = d.machineID;
                int machineLocationID = d.machineLocationID;
                int formType = d.formType;

                model = _machineManagementService.GetDetails(machineID, machineLocationID);
            }
            catch (Exception)
            {

            }

            return View(model);
        }


        #region Get data các tab

        [HttpGet]
        public JsonResult GetMachineErrorList(int machineID)
        {
            var data = _errorMachineService.GetErrorListByMachineID(machineID);
            return new JsonResult(data);
        }

        [HttpGet]
        public JsonResult GetSeriesTimeLine(int machineID)
        {
            // mặc định xem dữ liệu 24h gần nhất
            DateTime endDate = DateTime.Now;
            DateTime startDate = endDate.AddHours(-24);

            var data = _reportMachineRuningStatusService.GetListTimelineByMachineID(machineID, startDate, endDate);
            return new JsonResult(data);
        }

        [HttpGet]
        public JsonResult GetListStatusPercent(int machineID)
        {
            // mặc định xem dữ liệu 24h gần nhất
            DateTime endDate = DateTime.Now;
            DateTime startDate = endDate.AddHours(-24);

            var data = _reportMachineRuningStatusService.GetListStatusPercentByMachineID(machineID, startDate, endDate);
            return new JsonResult(data);
        }


        [HttpGet]
        public JsonResult GetListRepaireHistory(int machineID)
        {
            var data = _machineManagementService.GetMachineRepaireHistory(machineID);
            return new JsonResult(data);
        }

        [HttpGet]
        public JsonResult GetListMaintenanceChecklist(int machineID)
        {
            var data = _machineManagementService.GetMachineMaintenanceList(machineID);
            return new JsonResult(data);
        }
        #endregion
    }
}

WDI.OEE/Views/MachineManagement/MachineDetail.cshtml
@model Common.ViewModels.MachineDetailViewModel

<div class="col-xl-12 col-md-12">
    <div class="card">
        <div class="card-header">
            <h5>@(Model.Machine.MachineName ?? "Quản lý máy")</h5>
        </div>
        <div class="card-block tab-icon">
            <div class="row">
                <!-- [Tabs content] start -->
                <div class="col-lg-12 col-xl-12 col-md-12">
                    <!-- [Tabs menu] start -->
                    <ul class="nav nav-tabs md-tabs tab6" role="tablist">
                        <li class="nav-item">
                            <a class="nav-link active" data-toggle="tab" href="#tab_machinedetail" role="tab"><i class="tabname-icon icofont icofont-company"></i>Chi tiết máy</a>
                            <div class="slide"></div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" data-toggle="tab" href="#tab_accessory" role="tab"><i class="tabname-icon icofont icofont-wheel"></i>Linh kiện</a>
                            <div class="slide"></div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" data-toggle="tab" href="#tab_maintenance" role="tab"><i class="tabname-icon icofont icofont-tasks-alt"></i>Checklist bảo dưỡng</a>
                            <div class="slide"></div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" data-toggle="tab" href="#tab_operationtime" role="tab"><i class="tabname-icon icofont icofont-ui-settings"></i>Thời gian vận hành</a>
                            <div class="slide"></div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" data-toggle="tab" href="#tab_errorlist" role="tab"><i class="tabname-icon icofont icofont-exclamation-tringle"></i>Danh sách lỗi</a>
                            <div class="slide"></div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" data-toggle="tab" href="#tab_repairehistory" role="tab"><i class="tabname-icon icofont icofont-history"></i>Lich sử sửa chữa</a>
                            <div class="slide"></div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" data-toggle="tab" href="#tab_technicaldocument" role="tab"><i class="tabname-icon icofont icofont-history"></i>Tài liệu kỹ thuật</a>
                            <div class="slide"></div>
                        </li>
                    </ul>
                    <!-- [Tabs menu] end -->
                    <!-- [tabs content] start -->
                    <div class="tab-content card-block">
                        <!-- [Tab: Tab chi tiết máy] start -->
                        <div class="tab-pane active" id="tab_machinedetail" role="tabpanel">
                            @await Html.PartialAsync("_PartialMachineDetail", Model.Machine)
                        </div>
                        <!-- [Tab: Tab chi tiết máy] end -->
                        <!-- [Tab: Tab linh kiện] start -->
                        <div class="tab-pane" id="tab_accessory" role="tabpanel">
                            @await Html.PartialAsync("_PartialMachineComponent", Model.Machine.ListComponents)
                        </div>
                        <!-- [Tab: Tab linh kiện] end -->
                        <!-- [Tab: Tab checklist bảo dưỡng] start -->
                        <div class="tab-pane" id="tab_maintenance" role="tabpanel">
                            @await Html.PartialAsync("_PartialMachineMaintenanceCheklist", Model.Machine)
                        </div>
                        <!-- [Tab: Tab checklist bảo dưỡng] end -->
                        <!-- [Tab: Tab thời gian vận hành] start -->
                        <div class="tab-pane" id="tab_operationtime" role="tabpanel">
                            @await Html.PartialAsync("_PartialMachineRunningStatus", Model.Machine)
                        </div>
                        <!-- [Tab: Tab thời gian vận hành] end -->
                        <!-- [Tab: Tab danh sách lỗi] start -->
                        <div class="tab-pane" id="tab_errorlist" role="tabpanel">
                            @await Html.PartialAsync("_PartialMachineErrorList", Model.Machine)
                        </div>
                        <!-- [Tab: Tab danh sách lỗi] end -->
                        <!-- [Tab: Tab lịch sử sửa chữa] start -->
                        <div class="tab-pane" id="tab_repairehistory" role="tabpanel">
                            @await Html.PartialAsync("_PartialMachineRepaireHistory", Model.Machine)
                        </div>
                        <!-- [Tab: Tab lịch sử sửa chữa] end -->
                        <!-- [Tab: Tab tài liệu kỹ thuật] start -->
                        <div class="tab-pane" id="tab_technicaldocument" role="tabpanel">
                            @await Html.PartialAsync("_PartialMachineTechnicalDocument", Model.Machine)
                        </div>
                        <!-- [Tab: Tab tài liệu kỹ thuật] end -->
                    </div>
                    <!-- [tabs content] end -->
                </div>
                <!-- [Tabs content] end -->
            </div>
        </div>
        <div class="card-footer">
        </div>
    </div>
</div>

<script>
    $(document).ready(function () {

        // Xử lý tab click bị hiển thị duplicate
        $('a[data-toggle="tab"]').on('shown.bs.tab', function (e) {
            var target = $(e.target).attr("href") // activated tab
            console.log(target);

            // Clear active
            // Tìm cha của targe có class tab-content sau đó tìm all con của cha có class .tab-pane để bỏ class active
            $(target).closest('.tab-content').find('.tab-pane').removeClass('active');
            // $('.tab-pane').removeClass('active');

            // Active cho 1 tab thôi
            $(target).addClass('active');
        });
    });
</script>

WDI.OEE/Views/MachineManagement/_PartialMachineErrorList.cshtml
@model Common.Data_Machine

<div class="col-xl-12 col-sm-12">
    <div class="card">
        <div class="card-block table-border-style">
            <div class="table-responsive">
                <table id="gridListErrorMachine" class="table table-styling"
                       data-pagination="true"
                       data-page-list="[5, 10, 20, 50, 100, 200]"
                       data-show-footer="false">
                    <thead class="table-primary">
                        <tr>
                            <th data-field="errorDate" data-align="center" data-sortable="true" data-formatter="formatDateTime">Ngày</th>
                            <th data-field="machineName" data-align="left" data-sortable="true">Tên máy</th>
                            <th data-field="machineGroupName" data-align="left" data-sortable="true">Nhóm máy</th>
                            <th data-field="machineLocation" data-align="left" data-sortable="true">Vị trí</th>
                            <th data-field="errorCode" data-align="left" data-sortable="true">Mã lỗi</th>
                            <th data-field="errorName" data-align="left" data-sortable="true">Tên lỗi</th>
                            <th data-field="note" data-align="right" data-sortable="true">Ghi chú</th>
                        </tr>
                    </thead>
                </table>
            </div>
        </div>
    </div>
</div>


<script>
    $(document).ready(function () {
        var machineID = @Html.Raw(Json.Serialize(Model.MachineID));
        getMachineErrorList(machineID);
    });

    function getMachineErrorList(machineID) {
        $.ajax({
            url: '@Url.Action("GetMachineErrorList", "MachineManagement")' + '?machineID=' + machineID,
            method: "GET",
            dataType: "json",
            async: true,
            beforeSend: function () { },
            success: function (result) {
                if (result) {
                    $("#gridListErrorMachine").bootstrapTable({
                        data: result,
                        formatLoadingMessage: function () {
                            return '<b>Loading ...</b>';
                        }
                    });

                    $('#gridListErrorMachine').bootstrapTable('load', result);
                }
            },
            error: function (err) {
                console.log(err);
            }
        });
    }
</script>

WDI.OEE/Views/MachineManagement/_PartialMachineMaintenanceCheklist.cshtml
@model Common.Data_Machine


<div class="col-xl-12 col-sm-12">
    <div class="card">
        <div class="card-block table-border-style">
            <div class="table-responsive">
                <table id="gridMachineMaintenanceCheklist" class="table table-styling"
                       data-pagination="true"
                       data-page-list="[5, 10, 20, 50, 100, 200]"
                       data-show-footer="false">
                    <thead class="table-primary">
                        <tr>
                            <th data-field="content" data-align="left" data-sortable="true">Nội dung</th>
                            <th data-field="timeFinish" data-align="center" data-sortable="true" data-formatter="formatTimeMaintenanceInterval">Thời gian thực hiện</th>
                            <th data-field="intervalName" data-align="center" data-sortable="true">Tần suất thực hiện</th>
                            <th data-field="userGuide" data-align="left" data-sortable="true">Hướng dẫn thực hiện</th>
                            <th data-field="userGuideVideo" data-align="left" data-sortable="true">Video</th>
                        </tr>
                    </thead>
                </table>
            </div>
        </div>
    </div>
</div>



<script>
    $(document).ready(function () {
        var machineID = @Html.Raw(Json.Serialize(Model.MachineID));
        getListMaintenanceChecklist(machineID);
    });

    function getListMaintenanceChecklist(machineID) {
        $.ajax({
            url: '@Url.Action("GetListMaintenanceChecklist", "MachineManagement")' + '?machineID=' + machineID,
            method: "GET",
            dataType: "json",
            async: true,
            beforeSend: function () { },
            success: function (result) {
                if (result) {
                    $("#gridMachineMaintenanceCheklist").bootstrapTable({
                        data: result,
                        formatLoadingMessage: function () {
                            return '<b>Loading ...</b>';
                        }
                    });

                    $('#gridMachineMaintenanceCheklist').bootstrapTable('load', result);
                }
            },
            error: function (err) {
                console.log(err);
            }
        });
    }

    function formatTimeMaintenanceInterval(value, row, index) {
        return (value + ' (phút)');
    }
</script>

WDI.OEE/Views/MachineManagement/_PartialMachineRepaireHistory.cshtml
@model Common.Data_Machine

@if (Model != null)
{
    <div class="col-xl-12 col-sm-12">
        <div class="card">
            <div class="card-block table-border-style">
                <div class="table-responsive">
                    <table id="gridListMachineRepaireHistory" class="table table-styling"
                           data-pagination="true"
                           data-page-list="[5, 10, 20, 50, 100, 200]"
                           data-show-footer="false">
                        <thead class="table-primary">
                            <tr>
                                <th data-field="dateTaskAssigned" data-align="center" data-sortable="true" data-formatter="formatDateTime">Ngày</th>
                                <th data-field="errorCode" data-align="left" data-sortable="true">Mã lỗi</th>
                                <th data-field="executor" data-align="left" data-sortable="true">Nhân sự thực hiện</th>
                                <th data-field="dateFinishTask" data-align="center" data-sortable="true" data-formatter="formatDateTime">Ngày hoàn thành</th>
                            </tr>
                        </thead>
                    </table>
                </div>
            </div>
        </div>
    </div>
}
else
{
    <div>
        <span class="col-form-label">Máy chưa có lịch sử sửa chữa</span>
    </div>
}

<script>
    $(document).ready(function () {
        var machineID = @Html.Raw(Json.Serialize(Model.MachineID));
        getMachineRepaireHistory(machineID);
    });

    function getMachineRepaireHistory(machineID) {
        //debugger;
        $.ajax({
            url: '@Url.Action("GetListRepaireHistory", "MachineManagement")' + '?machineID=' + machineID,
            method: "GET",
            dataType: "json",
            async: true,
            beforeSend: function () { },
            success: function (result) {
                if (result) {
                    $("#gridListMachineRepaireHistory").bootstrapTable({
                        data: result,
                        formatLoadingMessage: function () {
                            return '<b>Loading ...</b>';
                        }
                    });

                    $('#gridListMachineRepaireHistory').bootstrapTable('load', result);
                }
            },
            error: function (err) {
                console.log(err);
            }
        });
    }
</script>

WDI.OEE/Views/MachineManagement/_PartialMachineRunningStatus.cshtml
@model Common.Data_Machine

<div class="card">
    <div class="card-body">
        <div class="row d-flex justify-content-center">
            <div class="col-lg-6 col-sm-12">
                <div id="rangebarchart"></div>
            </div>
            <div class="col-lg-6 col-sm-12">
                <canvas id="doughnutchart_timeline1" width="500" height="500"></canvas>
            </div>
        </div>
    </div>
</div>




<script>
    $(document).ready(function () {
        var machineID = @Html.Raw(Json.Serialize(Model.MachineID));
        
        // Chart 1
        $.ajax({
            url: '@Url.Action("GetSeriesTimeLine", "MachineManagement")?machineID='+machineID,
            method: "GET",
            dataType: "json",
            async: true,
            beforeSend: function () { },
            success: function (result) {
                if (result) {
                    create_rangebar_timeline('rangeBar', 'rangebarchart', result);
                }
            },
            error: function (err) {
                console.log('Lấy dữ liệu create_rangebar_timeline lỗi ::' + err);
            }
        });

        // Chart 2
        $.ajax({
            url: '@Url.Action("GetListStatusPercent", "MachineManagement")?machineID=' + machineID,
            method: "GET",
            dataType: "json",
            async: true,
            beforeSend: function () { },
            success: function (result) {
                if (result) {
                    create_polararea('doughnut', 'doughnutchart_timeline1', result);
                }
            },
            error: function (err) {
                console.log('Lấy dữ liệu doughnutchart_timeline lỗi ::' + err);
            }
        });
    });

    function create_rangebar_timeline(charttype, chartid, chartmodel) {

        var series = [{ data: chartmodel }];
        var options = {
            series: series,
            chart: {
                height: 250,
                type: 'rangeBar'
            },
            plotOptions: {
                bar: {
                    horizontal: true
                },
                minPointLength: 3
            },
            xaxis: {
                type: 'datetime'
            },
            tooltip: {
                custom: function (opts) {

                    const fromYear = getDateTime_LocalDateTimeString(new Date(opts.y1));
                    const toYear = getDateTime_LocalDateTimeString(new Date(opts.y2));


                    const w = opts.ctx.w
                    let ylabel = w.globals.labels[opts.dataPointIndex]
                    let seriesName = w.config.series[opts.seriesIndex].name
                        ? w.config.series[opts.seriesIndex].name
                        : ''
                    const color = w.globals.colors[opts.seriesIndex]
                    return (
                        '<div class="apexcharts-tooltip-rangebar">' +
                        '<div> <span class="series-name" style="color: ' +
                        color +
                        '"> Thời gian ' +
                        (seriesName ? seriesName : '') +
                        '</span></div>' +
                        '<div> <span class="category">' +
                        // ylabel +
                        ' </span> <span class="value start-value">' +
                        fromYear +
                        '</span> <span class="separator">-</span> <span class="value end-value">' +
                        toYear +
                        '</span></div>' +
                        '</div>'
                    )
                }
            }
        };

        var chart = new ApexCharts(document.querySelector('#' + chartid), options);
        chart.render();
    }

    function create_polararea(charttype, chartid, chartmodel) {
        var _chartlabels = ["Spring", "Summer", "Fall", "Winter"];
        var _chartdatas = [1200, 1700, 800, 200];
        var _chartbgcolor = ["rgba(255, 0, 0, 0.5)", "rgba(100, 255, 0, 0.5)", "rgba(200, 50, 255, 0.5)", "rgba(0, 100, 255, 0.5)"];
        var _charttype = charttype;
        if (_charttype === undefined || _charttype === null)
            _charttype = 'pie';

        // Nếu truyền model vào thì lấy giá trị của model
        if (chartmodel !== undefined
            && chartmodel !== null) {
            _chartlabels = [];
            _chartdatas = [];
            _chartbgcolor = [];
            chartmodel.forEach((value) => {
                _chartlabels.push(value.statusName);
                _chartdatas.push(value.dataPercent);
                _chartbgcolor.push(value.colorCode);
            });
        }


        new Chart($("#" + chartid), {
            type: 'polarArea',
            data: {
                labels: _chartlabels,
                datasets: [{
                    data: _chartdatas,
                    backgroundColor: _chartbgcolor,
                }]
            },
            options: {
                responsive: true,
                maintainAspectRatio: false,
                title: {
                    display: true,
                    text: 'Programming Language Usage on GeeksforGeeks'
                },
                plugins: {
                    legend: {
                        display: true,
                        position: 'bottom',
                        labels: {
                            generateLabels: (chart) => {
                                // Hiển thị con số ở label legend
                                const datasets = chart.data.datasets;
                                return datasets[0].data.map((data, i) => ({
                                    text: `${chart.data.labels[i]}: ${data}%`,
                                    fillStyle: datasets[0].backgroundColor[i],
                                }))
                            }
                        }
                    }
                }
            }
        });
    }
</script>

WDI.OEE/Views/MachineManagement/_PartialMachineTechnicalDocument.cshtml
@model Common.Data_Machine
@{
    //string _readonly_input = "";
}

<div class="row">
    <div class="col-xl-12 col-md-12">
        <div class="card table-card">
            <div class="card-header">
                <!--h5>Recent Tickets</h5>
                <div-- class="card-header-right">
                    <ul-- class="list-unstyled card-option">
                        <li><i class="fa fa fa-wrench open-card-option"></i></li>
                        <li><i class="fa fa-window-maximize full-card"></i></li>
                        <li><i class="fa fa-minus minimize-card"></i></li>
                        <li><i class="fa fa-refresh reload-card"></i></li>
                        <li><i class="fa fa-trash close-card"></i></li>
                    </ul>
                </div-->
            </div>
            <div class="card-block">
                <div class="table-responsive">
                    <table class="table table-hover table-borderless">
                        <thead>
                            <tr>
                                <th>Trạng thái</th>
                                <th>Tên file</th>
                                <th>Loại tài liệu</th>
                                <th>Ngày phát hành</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td><label class="label label-success">khả dụng</label></td>
                                <td><a href="@(Url.Action("DownloadBlank","File")+"?fName="+Model.MachineAssetCode+"_HDVH.pdf")" title="Tải file">@(Model.MachineAssetCode + "_HDVH.pdf")</a></td>
                                <td>Hướng dẫn vận hành</td>
                                <td>08/05/2024</td>
                            </tr>
                            <tr>
                                <td><label class="label label-primary">đang cập nhật</label></td>
                                <td><a href="@(Url.Action("DownloadBlank","File")+"?fName="+Model.MachineAssetCode+"_TLKT.pdf")" title="Tải file">@(Model.MachineAssetCode + "_TLKT.pdf")</a></td>
                                <td>Tài liệu kỹ thuật</td>
                                <td>12/05/2024</td>
                            </tr>
                            <tr>
                                <td><label class="label label-danger">đã xóa</label></td>
                                <td class="text-muted"><span href="@(Url.Action("DownloadBlank","File")+"?fName="+Model.MachineAssetCode+"_TLKT(v1).pdf")" title="Tải file">@(Model.MachineAssetCode + "_TLKT(v1).pdf")</span></td>
                                <td class="text-muted">Tài liệu kỹ thuật</td>
                                <td class="text-muted">03/04/2024</td>
                            </tr>
                            <tr>
                                <td><label class="label label-success">khả dụng</label></td>
                                <td><a href="@(Url.Action("DownloadBlank","File")+"?fName="+Model.MachineAssetCode+"_HDVH_2024.pdf")" title="Tải file">@(Model.MachineAssetCode + "_HDVH_2024.pdf")</a></td>
                                <td>Hướng dẫn vận hành</td>
                                <td>17/01/2024</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>